### ISSUE TITLE
NPM Version is outdated

### ISSUE THREAD

**Issue by AlinaNova21** [ashi009/node-qrencode-raw#3]
Hello, the NPM version is still using the older NAN code, its needing republished to get the newer NAN code from the last commits.

**Comment by AlinaNova21** [comment]
This is still outdated on NPM, any chance of a fresh publish?

**Comment by ashi009** [comment]
I'm sorry.  I have stopped working on any node related projects.  My node releated repos are most left unmaintained. 

Please send me a PR if you want and I'll merge.

**Comment by AlinaNova21** [comment]
The current code is working, its just not published to npm, I have to point to the repo rather than the npm in order to use this on newer node versions.

**Comment by ashi009** [comment]
oops, 0.2.0 published.

See ad039275a9506b58d06138d069104d9be1896049
